CREATE TABLE APP.STOCKS (
	TICKER    VARCHAR(10),
	PRICE     VARCHAR(10),
	DATE      VARCHAR(10),
	CHANGE    VARCHAR(10),
	LOW       VARCHAR(10),
	HIGH      VARCHAR(10),
	PRICEOPEN VARCHAR(10),
	VOLUME    VARCHAR(10)
);
